# A docker-compose must always start by the version tag.
version: "3"

# docker-composes works with services.
# In our case a server and a client, two services. # 1 service = 1 container.
services:

  # First service (container): the server.
  # you are free to choose the keyword.
  server-sec1:
    # The keyword "build" defines the path to the Dockerfile to use to create the image
    # that will allow you to execute the service.
    build: server-sec1/
    # The command to execute once the image is created.
    command: python ./server-sec1.py

    # Ports syntax: [port we want on our machine]:[port we want to retrieve in the container]
    # In our case, we want to use port 1234 on our machine and
    # retrieve port 1234 from the container (because it is on this port that
    # we broadcast the server).
    ports:
      - 1234:1234

  # Second service (container): the client.
  # you are free to choose the keyword.
  client-primary:
    build: client-primary/
    command: python ./client-primary.py

    # The keyword 'network_mode' is used to define the network type.
    # Here we define that the container can access to the 'localhost' of the computer.
    network_mode: host

    # The keyword'depends_on' allows you to define whether the service
    # should wait until other services are ready before launching.
    # Here, we want the 'client' service to wait until the 'server' service is ready.
    depends_on:
      - server-sec1