version: "3"

services:
  server-sec1:
    build:
      context: ./
      dockerfile: server-sec1/Dockerfile
    command: python ./server-sec1.py
    
    ports:
      - 50051:50051

  client-primary:
    build:
      context: ./
      dockerfile: client-primary/Dockerfile
    command: python ./client-primary.py
    
    network_mode: host

    depends_on:
      - server-sec1
