version: "3"

services:
  replicated_log_primary:
    build:
      context: .
      dockerfile: services/replicated_log_primary/Dockerfile
      args:
        HTTP_PORT: 9090
        GRPC_PORT: 9095

    environment:
      SECONDARY_1_ENABLED: "true"
      SECONDARY_1_HOST: "host.docker.internal"
      SECONDARY_1_PORT: 50052
      SECONDARY_1_ID: "secondary-1"

      SECONDARY_2_ENABLED: "true"
      SECONDARY_2_HOST: "host.docker.internal"
      SECONDARY_2_PORT: 8889
      SECONDARY_2_ID: "secondary-2"

      SHOULD_CHECK_QUORUM: "false"
      # Example of setting retry backoff configuration for different node statuses.
      REPLICATION_RETRIES_INITIAL_BACKOFF_UNHEALTHY: "PT10S"

    ports:
      - "9090:9090" # HTTP
      - "9095:9095" # GRPC

    depends_on:
      - replicated_log_secondary_1
      - replicated_log_secondary_2

    restart: unless-stopped

  replicated_log_secondary_1:
    build:
      context: .
      dockerfile: services/replicated_log_secondary_1/Dockerfile

    environment:
      NODE_ID: "secondary-1"
      PRIMARY_HOST: host.docker.internal
      PRIMARY_PORT: 9095

    ports:
      - "9091:5000" # HTTP
      - "50052:50051" # GRPC

    restart: unless-stopped

  replicated_log_secondary_2:
    build:
      context: .
      dockerfile: services/replicated_log_secondary_2/Dockerfile

    environment:
      NODE_ID: "secondary-2"
      INSERT_DELAY: "30s"
      PRIMARY_HOST: host.docker.internal
      PRIMARY_PORT: 9095

    ports:
      - "8888:8080" # HTTP
      - "8889:8081" # GRPC

    restart: unless-stopped
