version: "3"

services:
  replicated_log_primary:
    build:
      context: .
      dockerfile: services/replicated_log_primary/Dockerfile
      args:
        PORT: 9090

    environment:
      SECONDARY_1_ENABLED: "true"
      SECONDARY_1_HOST: host.docker.internal
      SECONDARY_1_PORT: 50052
      SECONDARY_2_ENABLED: "true"
      SECONDARY_2_HOST: host.docker.internal
      SECONDARY_2_PORT: 8889

    ports:
      - "9090:9090"

    depends_on:
      - replicated_log_secondary_1
      - replicated_log_secondary_2

    restart: unless-stopped

  replicated_log_secondary_1:
    build:
      context: .
      dockerfile: services/replicated_log_secondary_1/Dockerfile

    ports:
      - "9091:5000"
      - "50052:50051"

    restart: unless-stopped

  replicated_log_secondary_2:
    build:
      context: .
      dockerfile: services/replicated_log_secondary_2/Dockerfile

    environment:
      INSERT_DELAY: "30s"

    ports:
      - "8888:8080" # API
      - "8889:8081" # GRPC

    restart: unless-stopped
