replication:
  retries:
    defaults:
      initial-backoff: ${REPLICATION_RETRIES_DEFAULT_INITIAL_BACKOFF:PT1S}
      max-backoff: ${REPLICATION_RETRIES_DEFAULT_INITIAL_BACKOFF:PT5M}
    initial-backoff:
      HEALTHY: ${REPLICATION_RETRIES_INITIAL_BACKOFF_HEALTHY:PT1S}
      SUSPECTED: ${REPLICATION_RETRIES_INITIAL_BACKOFF_SUSPECTED:PT5S}
      UNHEALTHY: ${REPLICATION_RETRIES_INITIAL_BACKOFF_UNHEALTHY:PT15S}
    max-backoff:
      HEALTHY: ${REPLICATION_RETRIES_MAX_BACKOFF_HEALTHY:PT5M}
      SUSPECTED: ${REPLICATION_RETRIES_MAX_BACKOFF_SUSPECTED:PT5M}
      UNHEALTHY: ${REPLICATION_RETRIES_MAX_BACKOFF_UNHEALTHY:PT10M}

quarkus:
  # HTTP configuration.
  http:
    port: ${HTTP_PORT:9090}

  # GRPC configuration.
  grpc:
    server:
      port: ${GRPC_PORT:9095}

  # OpenAPI configuration.
  smallrye-openapi:
    info-title: Replicated Log Primary Node API
    info-version: 1.0.0
    info-description: Replicated Log Primary Node API

  swagger-ui:
    always-include: true
    path: /api/docs
