quarkus:
  # HTTP configuration.
  http:
    port: ${HTTP_PORT:9090}

  # GRPC configuration.
  grpc:
    server:
      port: ${GRPC_PORT:9095}

  # OpenAPI configuration.
  smallrye-openapi:
    info-title: Replicated Log Primary Node API
    info-version: 1.0.0
    info-description: Replicated Log Primary Node API

  swagger-ui:
    always-include: true
    path: /api/docs
