# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import replicated_log_pb2 as replicated__log__pb2


class ReplicatedLogStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReplicateMessages = channel.unary_unary(
                '/replicated_log.ReplicatedLog/ReplicateMessages',
                request_serializer=replicated__log__pb2.ReplicateMessagesRequest.SerializeToString,
                response_deserializer=replicated__log__pb2.ReplicateMessagesAck.FromString,
                )


class ReplicatedLogServicer(object):
    """Interface exported by the server.
    """

    def ReplicateMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicatedLogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReplicateMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateMessages,
                    request_deserializer=replicated__log__pb2.ReplicateMessagesRequest.FromString,
                    response_serializer=replicated__log__pb2.ReplicateMessagesAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replicated_log.ReplicatedLog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReplicatedLog(object):
    """Interface exported by the server.
    """

    @staticmethod
    def ReplicateMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/replicated_log.ReplicatedLog/ReplicateMessages',
            replicated__log__pb2.ReplicateMessagesRequest.SerializeToString,
            replicated__log__pb2.ReplicateMessagesAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
