# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replicated-log.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='replicated-log.proto',
  package='replicated_log',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14replicated-log.proto\x12\x0ereplicated_log\"+\n\x18ReplicateMessagesRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x14ReplicateMessagesAck\x12\x10\n\x08response\x18\x01 \x01(\t2v\n\rReplicatedLog\x12\x65\n\x11ReplicateMessages\x12(.replicated_log.ReplicateMessagesRequest\x1a$.replicated_log.ReplicateMessagesAck\"\x00\x62\x06proto3'
)




_REPLICATEMESSAGESREQUEST = _descriptor.Descriptor(
  name='ReplicateMessagesRequest',
  full_name='replicated_log.ReplicateMessagesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='replicated_log.ReplicateMessagesRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=83,
)


_REPLICATEMESSAGESACK = _descriptor.Descriptor(
  name='ReplicateMessagesAck',
  full_name='replicated_log.ReplicateMessagesAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='replicated_log.ReplicateMessagesAck.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['ReplicateMessagesRequest'] = _REPLICATEMESSAGESREQUEST
DESCRIPTOR.message_types_by_name['ReplicateMessagesAck'] = _REPLICATEMESSAGESACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReplicateMessagesRequest = _reflection.GeneratedProtocolMessageType('ReplicateMessagesRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPLICATEMESSAGESREQUEST,
  '__module__' : 'replicated_log_pb2'
  # @@protoc_insertion_point(class_scope:replicated_log.ReplicateMessagesRequest)
  })
_sym_db.RegisterMessage(ReplicateMessagesRequest)

ReplicateMessagesAck = _reflection.GeneratedProtocolMessageType('ReplicateMessagesAck', (_message.Message,), {
  'DESCRIPTOR' : _REPLICATEMESSAGESACK,
  '__module__' : 'replicated_log_pb2'
  # @@protoc_insertion_point(class_scope:replicated_log.ReplicateMessagesAck)
  })
_sym_db.RegisterMessage(ReplicateMessagesAck)



_REPLICATEDLOG = _descriptor.ServiceDescriptor(
  name='ReplicatedLog',
  full_name='replicated_log.ReplicatedLog',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=127,
  serialized_end=245,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReplicateMessages',
    full_name='replicated_log.ReplicatedLog.ReplicateMessages',
    index=0,
    containing_service=None,
    input_type=_REPLICATEMESSAGESREQUEST,
    output_type=_REPLICATEMESSAGESACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPLICATEDLOG)

DESCRIPTOR.services_by_name['ReplicatedLog'] = _REPLICATEDLOG

# @@protoc_insertion_point(module_scope)
